#!/usr/bin/env node
/**
 * Database Migration Script
 *
 * Automatically checks for and creates missing Better-Auth tables.
 * Runs on container startup before the main application.
 *
 * Usage: node scripts/db-migrate.mjs
 *
 * Environment:
 *   DATABASE_URL - PostgreSQL connection string (required)
 */

import pg from 'pg';

const { Pool } = pg;

// Better-Auth required tables
const BETTER_AUTH_TABLES = ['user', 'session', 'account', 'verification'];

// SQL to create Better-Auth tables
const MIGRATION_SQL = `
-- Better-Auth Core Schema
-- Auto-generated by db-migrate.mjs

-- User table - stores user information
CREATE TABLE IF NOT EXISTS "user" (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    image TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Session table - stores session data for authenticated users
CREATE TABLE IF NOT EXISTS "session" (
    id TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Account table - stores OAuth provider account links (Google, etc.)
CREATE TABLE IF NOT EXISTS "account" (
    id TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP WITH TIME ZONE,
    "refreshTokenExpiresAt" TIMESTAMP WITH TIME ZONE,
    scope TEXT,
    password TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Verification table - stores email verification and password reset tokens
CREATE TABLE IF NOT EXISTS "verification" (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_session_user_id ON "session"("userId");
CREATE INDEX IF NOT EXISTS idx_session_token ON "session"(token);
CREATE INDEX IF NOT EXISTS idx_session_expires ON "session"("expiresAt");
CREATE INDEX IF NOT EXISTS idx_account_user_id ON "account"("userId");
CREATE INDEX IF NOT EXISTS idx_account_provider ON "account"("providerId", "accountId");
CREATE INDEX IF NOT EXISTS idx_verification_identifier ON "verification"(identifier);
CREATE INDEX IF NOT EXISTS idx_verification_expires ON "verification"("expiresAt");
CREATE INDEX IF NOT EXISTS idx_user_email ON "user"(email);
`;

/**
 * Check which tables are missing from the database
 */
async function checkMissingTables(pool) {
  const query = `
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    AND table_name = ANY($1)
  `;

  const result = await pool.query(query, [BETTER_AUTH_TABLES]);
  const existingTables = result.rows.map(row => row.table_name);
  const missingTables = BETTER_AUTH_TABLES.filter(t => !existingTables.includes(t));

  return { existingTables, missingTables };
}

/**
 * Run database migrations
 */
async function runMigrations() {
  const databaseUrl = process.env.DATABASE_URL;

  if (!databaseUrl) {
    console.error('❌ DATABASE_URL environment variable is not set');
    process.exit(1);
  }

  console.log('🔄 Database Migration Check');
  console.log('━'.repeat(50));

  const pool = new Pool({ connectionString: databaseUrl });

  try {
    // Test connection
    console.log('📡 Connecting to database...');
    await pool.query('SELECT 1');
    console.log('✅ Database connection successful');

    // Check for missing tables
    console.log('\n🔍 Checking for Better-Auth tables...');
    const { existingTables, missingTables } = await checkMissingTables(pool);

    if (existingTables.length > 0) {
      console.log(`✅ Found tables: ${existingTables.join(', ')}`);
    }

    if (missingTables.length === 0) {
      console.log('✅ All Better-Auth tables exist - no migration needed');
      console.log('━'.repeat(50));
      return;
    }

    console.log(`⚠️  Missing tables: ${missingTables.join(', ')}`);
    console.log('\n🚀 Running migrations...');

    // Run migration SQL
    await pool.query(MIGRATION_SQL);

    // Verify tables were created
    const { missingTables: stillMissing } = await checkMissingTables(pool);

    if (stillMissing.length > 0) {
      console.error(`❌ Failed to create tables: ${stillMissing.join(', ')}`);
      process.exit(1);
    }

    console.log('✅ Migration completed successfully');
    console.log(`   Created tables: ${missingTables.join(', ')}`);
    console.log('━'.repeat(50));

  } catch (error) {
    console.error('❌ Migration failed:', error.message);

    // Provide helpful error messages
    if (error.code === 'ECONNREFUSED') {
      console.error('   → Database server is not reachable');
      console.error('   → Check if PostgreSQL is running and DATABASE_URL is correct');
    } else if (error.code === '28P01') {
      console.error('   → Authentication failed');
      console.error('   → Check your database credentials in DATABASE_URL');
    } else if (error.code === '3D000') {
      console.error('   → Database does not exist');
      console.error('   → Make sure the database has been created');
    }

    process.exit(1);
  } finally {
    await pool.end();
  }
}

// Run migrations
runMigrations();
